"""Markdown report rendering with a corroboration summary.

The report is the artifact an analyst hands to a reviewer, so it is built
around the one question a reviewer actually asks: *which claims are
corroborated, and by what?* Every finding is shown with its full
provenance, and each is assigned a status:

- ``CORROBORATED``   — two or more independent corroborating sources;
- ``PARTIAL``        — exactly one corroborating source;
- ``UNCORROBORATED`` — none. Presented as a lead, never as a claim.

Rendering is fully deterministic: findings are sorted by claim text, then
retrieval time, then source URL, so the same store always renders the
same document (modulo the injected generation timestamp). Deterministic
output is what makes a report diffable in review.
"""

from __future__ import annotations

from .worksheet import CORROBORATION_RULE

#: Corroboration count thresholds -> display status.
STATUS_CORROBORATED = "CORROBORATED"
STATUS_PARTIAL = "PARTIAL"
STATUS_UNCORROBORATED = "UNCORROBORATED"


def corroboration_status(finding: dict) -> str:
    """Classify one finding by how many independent sources back it.

    Expects an already-validated finding (see :mod:`h4ndl3.findings`);
    validation guarantees ``corroborated_by`` is a list free of the
    finding's own source URL, so a plain length check is sound here.
    """
    count = len(finding["corroborated_by"])
    if count >= 2:
        return STATUS_CORROBORATED
    if count == 1:
        return STATUS_PARTIAL
    return STATUS_UNCORROBORATED


def _sort_key(finding: dict) -> tuple[str, str, str]:
    """Deterministic ordering: claim, then retrieval time, then source."""
    return (
        finding["claim"].casefold(),
        finding["retrieved_at_utc"],
        finding["source_url"],
    )


def render_report(
    findings: list[dict],
    *,
    generated_at_utc: str,
    title: str = "Identifier Research Report",
) -> str:
    """Render findings to a Markdown report with a corroboration summary.

    Args:
        findings: Validated findings, any order (they are sorted here).
        generated_at_utc: Injection point for the clock, for reproducible
            renders and tests.
        title: Report heading; defaults to a neutral professional title.

    Returns:
        The report as a Markdown string. An empty store renders a valid
        report that says so plainly — silence must never masquerade as
        an empty result set.
    """
    ordered = sorted(findings, key=_sort_key)

    counts = {
        STATUS_CORROBORATED: 0,
        STATUS_PARTIAL: 0,
        STATUS_UNCORROBORATED: 0,
    }
    confidence_counts = {level: 0 for level in ("low", "medium", "high")}
    for finding in ordered:
        counts[corroboration_status(finding)] += 1
        confidence_counts[finding["confidence"]] += 1

    lines = [
        f"# {title}",
        "",
        f"- Generated (UTC): {generated_at_utc}",
        f"- Findings: {len(ordered)}",
        "",
        "## Corroboration summary",
        "",
        f"> {CORROBORATION_RULE}",
        "",
        "| Status | Findings |",
        "|---|---:|",
        f"| {STATUS_CORROBORATED} | {counts[STATUS_CORROBORATED]} |",
        f"| {STATUS_PARTIAL} | {counts[STATUS_PARTIAL]} |",
        f"| {STATUS_UNCORROBORATED} | {counts[STATUS_UNCORROBORATED]} |",
        "",
        "| Confidence | Findings |",
        "|---|---:|",
        f"| high | {confidence_counts['high']} |",
        f"| medium | {confidence_counts['medium']} |",
        f"| low | {confidence_counts['low']} |",
        "",
        "## Findings",
        "",
    ]

    if not ordered:
        lines += [
            "_No findings recorded._",
            "",
        ]
    for index, finding in enumerate(ordered, start=1):
        status = corroboration_status(finding)
        lines += [
            f"### {index}. {finding['claim']}",
            "",
            f"- Status: **{status}**",
            f"- Confidence: {finding['confidence']}",
            f"- Source: {finding['source_url']}",
            f"- Retrieved (UTC): {finding['retrieved_at_utc']}",
        ]
        corroborated_by = finding["corroborated_by"]
        if corroborated_by:
            lines.append("- Corroborated by:")
            for url in corroborated_by:
                lines.append(f"  - {url}")
        else:
            # An explicit absence reads better in review than a silently
            # missing section, and it reinforces the corroboration rule.
            lines.append("- Corroborated by: _none recorded — treat as a lead, not a claim_")
        if finding.get("notes"):
            lines.append(f"- Notes: {finding['notes']}")
        lines.append("")

    lines += [
        "---",
        "",
        "_Generated by h4ndl3. Findings are analyst-recorded observations "
        "of public sources; this report asserts provenance, not identity._",
        "",
    ]
    return "\n".join(lines)
