"""Shell completion scripts for the ``chr0nix`` dispatcher.

Static, dependency-free completion for bash and zsh, printed by
``chr0nix completion bash|zsh`` and shipped verbatim under
``completions/``. The word lists are deliberately hand-maintained:
completion is a convenience, not a parser, so it completes the
dispatcher's top-level commands and the second-level words of the
``case`` / ``guide`` / ``timeline`` groups (plus the passthrough
groups' subcommands) and nothing more — no filesystem probing, no
dynamic evaluation of anything at completion time.

When commands change, update the tuples below and regenerate the
shipped files::

    chr0nix completion bash > completions/chr0nix.bash
    chr0nix completion zsh  > completions/chr0nix.zsh

The tests pin the word lists against the scripts, so drift fails loudly.
"""

#: Top-level dispatcher commands (see chr0nix/cli.py).
TOP_LEVEL = (
    "console", "manifest", "verify", "custody", "timeline",
    "worksheet", "add", "validate", "report", "extract", "batch",
    "case", "guide", "cust0dia", "h4ndl3", "m3talex", "completion",
)

#: Second-level words per group command.
SECOND_LEVEL = {
    "case": (
        "init", "new", "list", "show", "status", "categorize", "classify",
        "entity", "link", "associations", "event", "inbox", "file",
        "statement", "synopsis", "export",
    ),
    "guide": ("list", "show", "capture"),
    "timeline": ("build", "schema"),
    "cust0dia": ("manifest", "verify", "custody"),
    "h4ndl3": ("worksheet", "add", "validate", "report", "manifest"),
    "m3talex": ("extract", "batch"),
    "completion": ("bash", "zsh"),
}

#: Third level: the argument words worth completing under `case`.
CASE_THIRD_LEVEL = {
    "entity": ("add", "set", "show", "list"),
    "statement": ("record", "sign", "list"),
    "status": ("draft", "pending", "submitted", "referred", "closed"),
}


def bash_script() -> str:
    """The bash completion script (``complete -F`` on ``chr0nix``)."""
    top = " ".join(TOP_LEVEL)
    lines = [
        "# bash completion for chr0nix — generated by `chr0nix completion bash`.",
        "# Install: chr0nix completion bash > ~/.local/share/bash-completion/completions/chr0nix",
        "# (or: source it from ~/.bashrc). Static word lists; no runtime probing.",
        "",
        "_chr0nix() {",
        '    local cur',
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        "",
        f'    local commands="{top}"',
        '    if [ "$COMP_CWORD" -eq 1 ]; then',
        '        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )',
        "        return 0",
        "    fi",
        "",
        '    case "${COMP_WORDS[1]}" in',
    ]
    for group, words in SECOND_LEVEL.items():
        joined = " ".join(words)
        lines += [
            f"        {group})",
            '            if [ "$COMP_CWORD" -eq 2 ]; then',
            f'                COMPREPLY=( $(compgen -W "{joined}" -- "$cur") )',
        ]
        if group == "case":
            lines += [
                '            elif [ "$COMP_CWORD" -eq 3 ]; then',
                '                case "${COMP_WORDS[2]}" in',
            ]
            for sub, third in CASE_THIRD_LEVEL.items():
                lines.append(
                    f'                    {sub}) COMPREPLY=( $(compgen -W "{" ".join(third)}" -- "$cur") ) ;;'
                )
            lines += ["                esac", "            fi", "            ;;"]
        else:
            lines += ["            fi", "            ;;"]
    lines += [
        "    esac",
        "    return 0",
        "}",
        "",
        "complete -F _chr0nix chr0nix",
        "",
    ]
    return "\n".join(lines)


def zsh_script() -> str:
    """The zsh completion script (``#compdef chr0nix``)."""
    top = " ".join(TOP_LEVEL)
    lines = [
        "#compdef chr0nix",
        "# zsh completion for chr0nix — generated by `chr0nix completion zsh`.",
        "# Install: chr0nix completion zsh > ~/.zfunc/_chr0nix  (a directory on",
        "# $fpath), then `autoload -Uz compinit && compinit`. Static word lists.",
        "",
        "_chr0nix() {",
        "    local -a commands",
        f'    commands=({top})',
        "",
        "    if (( CURRENT == 2 )); then",
        "        compadd -- $commands",
        "        return",
        "    fi",
        "",
        '    case "$words[2]" in',
    ]
    for group, words in SECOND_LEVEL.items():
        pattern = f'"{group}"' if group == "case" else group
        lines.append(f"        {pattern})")
        lines.append(f"            if (( CURRENT == 3 )); then")
        lines.append(f'                compadd -- {" ".join(words)}')
        if group == "case":
            lines.append("            elif (( CURRENT == 4 )); then")
            lines.append('                case "$words[3]" in')
            for sub, third in CASE_THIRD_LEVEL.items():
                lines.append(f'                    {sub}) compadd -- {" ".join(third)} ;;')
            lines += ["                esac", "            fi"]
        else:
            lines.append("            fi")
        lines.append("        ;;")
    lines += [
        "    esac",
        "}",
        "",
        '_chr0nix "$@"',
        "",
    ]
    return "\n".join(lines)


def script_for(shell: str) -> str:
    """The completion script for ``shell`` (``bash`` or ``zsh``)."""
    return {"bash": bash_script, "zsh": zsh_script}[shell]()
