# bash completion for chr0nix — generated by `chr0nix completion bash`.
# Install: chr0nix completion bash > ~/.local/share/bash-completion/completions/chr0nix
# (or: source it from ~/.bashrc). Static word lists; no runtime probing.

_chr0nix() {
    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"

    local commands="console manifest verify custody timeline worksheet add validate report extract batch case guide cust0dia h4ndl3 m3talex completion"
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
        return 0
    fi

    case "${COMP_WORDS[1]}" in
        case)
            if [ "$COMP_CWORD" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "init new list show status categorize classify entity link associations event inbox file statement synopsis export" -- "$cur") )
            elif [ "$COMP_CWORD" -eq 3 ]; then
                case "${COMP_WORDS[2]}" in
                    entity) COMPREPLY=( $(compgen -W "add set show list" -- "$cur") ) ;;
                    statement) COMPREPLY=( $(compgen -W "record sign list" -- "$cur") ) ;;
                    status) COMPREPLY=( $(compgen -W "draft pending submitted referred closed" -- "$cur") ) ;;
                esac
            fi
            ;;
        guide)
            if [ "$COMP_CWORD" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "list show capture" -- "$cur") )
            fi
            ;;
        timeline)
            if [ "$COMP_CWORD" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "build schema" -- "$cur") )
            fi
            ;;
        cust0dia)
            if [ "$COMP_CWORD" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "manifest verify custody" -- "$cur") )
            fi
            ;;
        h4ndl3)
            if [ "$COMP_CWORD" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "worksheet add validate report manifest" -- "$cur") )
            fi
            ;;
        m3talex)
            if [ "$COMP_CWORD" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "extract batch" -- "$cur") )
            fi
            ;;
        completion)
            if [ "$COMP_CWORD" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") )
            fi
            ;;
    esac
    return 0
}

complete -F _chr0nix chr0nix
