#compdef chr0nix
# zsh completion for chr0nix — generated by `chr0nix completion zsh`.
# Install: chr0nix completion zsh > ~/.zfunc/_chr0nix  (a directory on
# $fpath), then `autoload -Uz compinit && compinit`. Static word lists.

_chr0nix() {
    local -a commands
    commands=(console manifest verify custody timeline worksheet add validate report extract batch case guide cust0dia h4ndl3 m3talex completion)

    if (( CURRENT == 2 )); then
        compadd -- $commands
        return
    fi

    case "$words[2]" in
        "case")
            if (( CURRENT == 3 )); then
                compadd -- init new list show status categorize classify entity link associations event inbox file statement synopsis export
            elif (( CURRENT == 4 )); then
                case "$words[3]" in
                    entity) compadd -- add set show list ;;
                    statement) compadd -- record sign list ;;
                    status) compadd -- draft pending submitted referred closed ;;
                esac
            fi
        ;;
        guide)
            if (( CURRENT == 3 )); then
                compadd -- list show capture
            fi
        ;;
        timeline)
            if (( CURRENT == 3 )); then
                compadd -- build schema
            fi
        ;;
        cust0dia)
            if (( CURRENT == 3 )); then
                compadd -- manifest verify custody
            fi
        ;;
        h4ndl3)
            if (( CURRENT == 3 )); then
                compadd -- worksheet add validate report manifest
            fi
        ;;
        m3talex)
            if (( CURRENT == 3 )); then
                compadd -- extract batch
            fi
        ;;
        completion)
            if (( CURRENT == 3 )); then
                compadd -- bash zsh
            fi
        ;;
    esac
}

_chr0nix "$@"
